"""<meaningful message>

Revision ID: c16f10480038
Revises: 676d13fb7131
Create Date: 2021-03-21 11:26:40.486580

"""
from alembic import op
import sqlalchemy as sa
from alembic import context
import sys
sys.path = ['', '..'] + sys.path[1:]


# revision identifiers, used by Alembic.
revision = 'c16f10480038'
down_revision = '676d13fb7131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
